language: node_js
node_js:
  - "10"
  - "12"
  - "14"
services:
  - "postgresql"
before_script:
  - npm install
  - psql -c 'CREATE DATABASE node_test_travis;' -U postgres
script:
  - npm test
env:
  global:
    - NODE_ENV=test
  matrix:
    - DATABASE_URL=postgres://postgres@localhost/node_test_travis